### ISSUE TITLE
Allow the developer to send secure cookies no matter what

### ISSUE THREAD

**Issue by fengmk2** [pillarjs/cookies#51]
Because my nodejs app behind an nginx. 

```
Browser == https ==> nginx == http ==> nodejs app
```

So `req.protocol` always be `http`, then I `cookies.set(name, value, {secure: true}` it throw `Cannot send secure cookie over unencrypted connection` Error.

**Comment by RHavar** [comment]
What's the status of this? How is everyone else working around this? It's pretty common to use SaaS providers, like heroku to have an unencrypted connection between their load balancer and your app. As well doing SSL termination in nginx and what not.

**Comment by dougwilson** [comment]
They are using Express or something else that updates req.protocol based on the reverse proxy.

**Comment by dougwilson** [comment]
As a side-note, this issue wasn't assigned to me, so I didn't even remember it existed. That's fixed now.

**Comment by fengmk2** [comment]
me too …

**Comment by atian25** [comment]
@fengmk2 it seem this still happen in koa

**Comment by djbobbydrake** [comment]
Has anyone solved this issue for koa?

**Comment by dougwilson** [comment]
This issue, "Allow the developer to send secure cookies no matter what" is already fixed in the version 0.6.0 release. Just set `secure: true` in your `Cookies` constructor and then this module will assume the request is secure for setting secure cookie and will not examine the request itself.

**Comment by malliapi** [comment]
Why does this library add secure to the cookie when new Cookies(req, res, {secure: true}). I simply want to bypass the check but not alter my cookie !!!

**Comment by tiagocpontesp** [comment]
FYI this isn't working through `.set(..., opts)`, on the latest version.

**Comment by pecliu** [comment]
> FYI this isn't working through `.set(..., opts)`, on the latest version.

Me too.  setting `secure: true` in`ctx.cookies.set(..., opts)` doesn't work, still throw `Cannot send secure cookie over unencrypted connection`

**Comment by dougwilson** [comment]
You need to construct it with the override first: `cookies = new Cookies( request, response, { secure: true })`
